version: '3.8'

services:
  database:
    container_name: db_pruefungsverwaltung
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: spring
      MYSQL_DATABASE: spring
      MYSQL_USER: spring
      MYSQL_PASSWORD: spring
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
